### ISSUE TITLE
Check type of returns and their usage

### ISSUE THREAD

**Issue by german1608** [aitorres/firelink#31]
Functions should check that return statements have expressions and their types should match with the function data type.

**Comment by aitorres** [comment]
Currently working on this, such that:

- Return-with-expression instructions cannot be used outside of a function (not in procedures nor in the main body)
- Return-with-expression instructions inside a function are type-checked properly
- Return-without-expression is NOT used inside a function, only on procedures or the main body

Partial work pushed on branch `feature/return-type-checking`

**Comment by aitorres** [comment]
To do list:
- [ ] Do expression casting before checking
- [ ] Retrieve types properly, don't compare string representations
- [ ] Test with aliases
- [ ] Specify in specs that returns can't go in functions, and returns with expressions only go in functions
- [ ] Add tests
- [ ] Run / fix previous tests
