### ISSUE TITLE
Define a way to interact with `union` data types

### ISSUE THREAD

**Issue by german1608** [aitorres/firelink#43]
We need a statement or something to know in an specific moment what option an `union` variable has. For example,
```c
union {int a; char b} c;
c.a = 1; // the value on c.b is overriden
c.b = 'a'; // the value on c.a is overriden
if (c.a is active) ... else ...
```

**Comment by aitorres** [comment]
Could we add a generic `typeOf` function that returns a string representation of the given type? `c.a is active` would just be `type c == 'humanity'` or something like that, and we could use that in other places as well.
