### ISSUE TITLE
Error module: centralizing errors in the project

### ISSUE THREAD

**Issue by german1608** [aitorres/firelink#5]
We need to centralize all compilers errors in the project, a file named `Errors.hs` with an only data type `CompilerError` that derives from `Show` would be ideal.

The errors that we need to handle are the following:
- Lexer errors:
  - "Did you mean this token instead of this?" kind of errors
  - General errors
- Parser errors:
  - For the moments, just a simple parse error
- Semantic errors:
  - Variable redeclaration on the same declaration block
  - Name not found:
    - For functions
    - For variables
    - For accesing properties that does not exists on a variable of type `bezel` or `link`.

**Comment by aitorres** [comment]
Closed some time ago by #51
