### ISSUE TITLE
Type alias name conflicts

### ISSUE THREAD

**Issue by aitorres** [aitorres/firelink#60]
Currently, running our compiler with the [test.souls](samples/correct/test.souls) file generates three errors, one of them being:

![Screenshot_20200128_230256](https://user-images.githubusercontent.com/26191851/73324752-72c42580-4222-11ea-98a7-dfc805e0503d.png)

We should either fix the file or discuss if we should allow variables to be named as type aliases (I can't remember if we have already talked about this).

**Comment by german1608** [comment]
It is intentional. Aliases names can't be reused to declare other names

**Comment by german1608** [comment]
We should add that to our spec.md
